version: "3.8"

services:
  nestjs:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - NODE_ENV=development
      - SERVER_PORT=${SERVER_PORT}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  postgres:
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"

  redis:
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"
