version: "3.8"

services:
  nginx:
    restart: always

  frontend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - SERVER_PORT=${SERVER_PORT}
    restart: always

  postgres:
    restart: always

  redis:
    restart: always
