version: "3.8"

services:
  nestjs:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}

  postgres:
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
